# Generated by Django 3.0.3 on 2020-11-11 18:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('has_started_program', models.BooleanField(default=False, editable=False, verbose_name='has started program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('height', models.CharField(help_text='in metres', max_length=255, null=True, verbose_name='height')),
                ('weight', models.CharField(help_text='in kgs', max_length=255, null=True, verbose_name='weight')),
                ('date_of_birth', models.DateField(null=True, verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=8, verbose_name='gender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='has_generated_report',
            field=models.BooleanField(default=False, verbose_name='has generated end of program report'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='user',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('trust_more_and_stress_less', 'Trust More And Stress Less'), ('have_refreshing_rest', 'Have Refreshing Rest'), ('enjoy_sunlight', 'Enjoy Sunlight'), ('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('water', 'Water'), ('live_temperately', 'Live Temperately'), ('invest_in_others', 'Invest In Others'), ('fresh_air', 'Fresh Air'), ('education', 'Education'), ('super_challenge', 'Super Challenge')], max_length=256), blank=True, default=list, null=True, size=None, verbose_name='topics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email adress'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('name', 'corporate'), name='unique_named_user'),
        ),
        migrations.AddField(
            model_name='user',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.Corporation', verbose_name='corporate'),
        ),
    ]
