# Generated by Django 3.0.3 on 2020-11-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('trust_more_and_stress_less', 'Trust More And Stress Less'), ('have_refreshing_rest', 'Have Refreshing Rest'), ('enjoy_sunlight', 'Enjoy Sunlight'), ('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('water', 'Water'), ('live_temperately', 'Live Temperately'), ('invest_in_others', 'Invest In Others'), ('fresh_air', 'Fresh Air'), ('education', 'Education'), ('super_challenge', 'Super Challenge')], max_length=32, verbose_name='category')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('is_super', models.BooleanField(blank=True, default=False, verbose_name='is super')),
                ('score', models.PositiveSmallIntegerField(blank=True, default=(1,), verbose_name='score')),
                ('URLName', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
